config/routes.rb
RainforestAttempt2::Application.routes.draw do

  root :to => 'products#index'

  resources :products do

    resources :reviews, only: [:create, :destroy, :edit, :update]

  end 

  resources :users, only: [:new, :create, :destroy, :show]

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base

    has_many :reviews
    belongs_to :user

    validates :name, :presence => true
    validates :description, :presence => true
    validates :category, :presence => true
    validates :image_url, :presence => true
    validates :price, :presence => true


    def show_price

        price_dollars = price/100.00

        sprintf("$%.2f",price_dollars)

    end 


end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :product
    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

    has_many :reviews
    has_many :products
    has_one :userinfo

    has_secure_password

    validates :user_name, :presence => true, :length => { minimum: 5}


end

app/models/userinfo.rb
class Userinfo < ActiveRecord::Base

    belongs_to :user

    validates :first_name, :presence => true
    validates :last_name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  SESSION_EXPIRY_MINUTES = 15

  private

    def authenticate

    @authenticated = (Userinfo.find_by(user_id: session[:user_id], active_status: 1) != nil) && ((session[:expire_on] ||= '9999-12-31') && session[:expire_on] >= Time.now)

    puts '---------------------------------'
    puts @authenticated
    puts session[:user_id]
    puts '---------------------------------'
    end 



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    before_filter :authenticate

    def index

        @products = Product.all

    end 

    def show

        @product = Product.find_by(id: params[:id])

        @reviews = @product.reviews.order(:created_at => :desc)

        @user = session[:user_id]
        
    end 

    def new
    
        @product = Product.new
        flash[:user_id] = session[:user_id] #passing the user ID so that it can be logged with the product in the create action

    end 

    def create

        @product = Product.new(product_params.merge(user_id: flash[:user_id]))
        
        unless @product.price.nil?
        @product.price = (@product.price * 100).to_i
         end

        if @product.save
            redirect_to product_path(@product)
        else 
            
            @errors = @product.errors.messages

            render 'new'

        end 

    end 


    def user_index

        @products = User.find_by(id: session[:user_id]).products

    end 

    def edit

        @product = Product.find_by(id: params[:id])

    end 

    def update

        @product = Product.find_by(id: params[:id])

        if @product.update_attributes(product_params)
            redirect_to products_path
        else 
            render action: :edit
        end 

    end 

    def destroy

        Product.destroy(params[:id])

        redirect_to products_path

    end 

    private

    def product_params

        params.require(:product).permit(:name,:category,:price,:description,:image_url)

    end 

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_filter :authenticate

    def create

        @product = Product.find_by(id: params[:product_id])

        @product.reviews.new(review_params).save

        redirect_to product_path(@product)

    end 


    def edit

        @product = Product.find_by(id: params[:product_id])
        @review = Review.find_by(id: params[:id])
        @user = session[:user_id]

    end 


    def update

        @product = Product.find_by(id: params[:product_id])
        @review = @product.reviews.find_by(id: params[:id])

        @review.update_attributes(review_params)

        redirect_to product_path(@product)

    end

    def destroy

        @product = Product.find_by(id: params[:product_id])
        @product.reviews.find_by(id: params[:id]).delete

        redirect_to product_path(@product)

    end 


    private

    def review_params

        params.require(:review).permit(:title, :content, :user_id)

    end 

end

app/controllers/session_controller.rb
class SessionsController < ApplicationController


    def new
        
        puts '-------------------------------------------'
        # puts params
        puts '-------------------------------------------'
        @redirect_source = params[:redirect_source]


    end 


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def new

        @redirect_source = params[:redirect_source]

    end 

    def create

        user = User.where(user_name: params[:user_name]).joins(:userinfo).merge(Userinfo.where(active_status:1)).take

        if user && user.authenticate(params[:password])

            session[:user_id] = user.id
            session[:expire_on] = SESSION_EXPIRY_MINUTES.minutes.from_now

            redirect_to params[:redirect_source] == nil ? products_path : params[:redirect_source]

        else

            render action: 'new'

        end 

    end 


    def destroy
    
        session[:user_id] = nil
        redirect_to products_path

    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_filter :authenticate

    def new
        @user = User.new
    end 

    def create

        @user = User.new(user_params)

        if @user.save 
            @user_info = Userinfo.new(userinfo_params)
            @user_info.user_id = @user.id

                if @user_info.save
                session[:user_id] = @user.id
                session[:expire_on] = SESSION_EXPIRY_MINUTES.minutes.from_now
                redirect_to products_path, :notice => "Sign up successful. Welcome #{@user.userinfo.first_name}!"
                else
                
                User.delete(@user)
                @user = User.new

                @errors = @user_info.errors.messages

                render :action => :new

                end
        else

            @errors = @user.errors.messages

            render :action => :new
        end

    end 


    def destroy

        @user_id = params[:id]

        Userinfo.find_by(user_id: @user_id).update_attributes(active_status: 0)

        redirect_to products_path

    end 

    def show

        @user = User.find_by(id:params[:id])
        @user_info = @user.userinfo
        @count_products = @user.products.count
        @count_reviews = @user.reviews.count

        @products = @user.products

    end 

    private

    def user_params

        params.require(:user).permit(:user_name,:password,:password_confirmation)

    end  

    def userinfo_params

        params.require(:userinfo).permit(:first_name,:last_name,:active_status)

    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RainforestAttempt2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<p>Welcome back <%= User.find_by(id: session[:user_id]).user_name %>! <%= link_to "Log out", session_path('current'), method: 'delete' %></p>

<h1>Edit the your product below:</h1>

 <%= render 'shared/product_info' %>

app/views/products/index.html.erb
<% if @authenticated %>

    <% if flash[:notice] %>

        <p><%= flash[:notice] %> <%= link_to "Log out", session_path('current'), method: 'delete' %> <%= link_to "Delete my account", user_path(session[:user_id]), method:'delete' %> <%= link_to "See my products" %> <%= link_to "Add a product", new_product_path %></p>

    <% else %>

    <p><%= render "shared/top_banner" %></p>

    <% end %>

<% else %>

<p><%= link_to "Sign up", new_user_path %> or <%= link_to "Log in", new_session_path %> </p>

<% end %>

<h1>Here are all products:</h1>

<%= render "shared/show_products" %>

app/views/products/new.html.erb
<p>Welcome back <%= Userinfo.find_by(user_id: session[:user_id]).first_name.capitalize %>! <%= link_to "Log out", session_path('current'), method: 'delete' %></p>

<p><%= link_to "Back", products_path%></p>

<h1>Add your product below:</h1>

<% if @errors %>

    <% @errors.each do |error| %>

        <b><p><%= error.join(" ") %></p></b>

    <% end %>    

<% end %>

<%= render 'shared/product_info' %>

app/views/products/show.html.erb
<% if @authenticated %>

    <p><%= render "shared/top_banner" %></p>

<% else %>

<p><%= link_to "Sign up", new_user_path %> or <%= link_to "Log in", "/sessions/new?redirect_source=/products/#{@product.id}" %></p>

<% end %>
<p><%= link_to "Back", products_path %></p>

<h1>Here are the details for <%= @product.name %>:</h1>

    <%= image_tag(@product.image_url, height: "360")  %>

    <p><%= @product.name %></p>
    <p><%= @product.category %></p>
    <p><%= @product.description %></p>
    <p><%= @product.show_price %></p>
            
    <% if @authenticated %>
        <% if User.find_by(id:session[:user_id]).products.include?(@product) %>

            <p><%= link_to "Update", edit_product_path(@product) %> <%= link_to "Delete", product_path(@product), method:'delete' %></p>

        <% end %>
    <% end %>

<% @reviews.each do |review| %>


    <h3><%= review.title %></h3>
    <p><%= review.content %></p>
    <p>Submitted by <%= review.user.userinfo.first_name + " " + review.user.userinfo.last_name %> on <%= review.created_at %></p>

    <% if @authenticated %>
        <% if User.find_by(id:session[:user_id]).reviews.include?(review) %>

            <p><%= link_to "Update", edit_product_review_path(@product,review) %> <%= link_to "Delete", product_review_path(@product,review), method:'delete' %></p>

        <% end %>
    <% end %>
 


<% end %>

<% if @authenticated %>

    <h2>Submit a review for this product:</h2>

    <%= form_for [@product, @product.reviews.new] do |f| %>

        <p><%= f.label 'title', 'Title' %></p>
        <p><%= f.text_field 'title' %></p>

        <p><%= f.label 'content', 'Review' %></p>
        <p><%= f.text_area 'content' %></p>

        <p><%= f.hidden_field 'user_id', value: @user %></p>

        <p><%= f.submit 'Submit review' %></p>

    <% end %>

<% else %>

    <p><%= link_to "Log in", "/sessions/new?redirect_source=/products/#{@product.id}" %> to submit a review</p>

<% end %>

app/views/reviews/edit.html.erb
<% if @authenticated %>
<%= render 'shared/top_banner' %>
<% end %>

<p><%= link_to "Back", product_path(@product) %></p>

<h1>Update your review below:</h1>

    <%= form_for [@product, @review] do |f| %>

        <p><%= f.label 'title', 'Title' %></p>
        <p><%= f.text_field 'title' %></p>

        <p><%= f.label 'content', 'Review' %></p>
        <p><%= f.text_area 'content' %></p>

        <p><%= f.hidden_field 'user_id', value: @user %></p>

        <p><%= f.submit 'Swubmit review' %></p>

    <% end %>

app/views/shared/_product_info.html.erb
<%= form_for @product do |f| %>

    <p><%= f.label 'name', "Product name" %></p>
    <p><%= f.text_field 'name' %></p>

    <p><%= f.label 'category', "Category" %></p>
    <p><%= f.text_field 'category' %></p>

    <p><%= f.label 'price', "Unit Price" %></p>
    <p><%= f.text_field 'price' %></p>


    <p><%= f.label 'description', "Product description" %></p>
    <p><%= f.text_area 'description' %></p>

    <p><%= f.label 'image_url', "Image URL" %></p>
    <p><%= f.text_field 'image_url' %></p>

    <%= f.hidden_field 'user_id', value:session[:user_id] %>

    <p><%= f.submit %></p>

<% end %>

app/views/shared/_show_products.html.erb
<% @products.each do |product| %>

    <%= link_to image_tag(product.image_url, height: "180"), product_path(product) %>

    <p><%= product.name %></p>
    <p><%= product.category %></p>
    <p><%= product.description %></p>
    <p><%= product.show_price %></p>

    <% if @authenticated %>
        <% if User.find_by(id:session[:user_id]).products.include?(product) %>


            <p><%= link_to "Update", edit_product_path(product) %> <%= link_to "Delete", product_path(product), method:'delete' %></p>

        <% end %>
    <% end %>

<% end %>

app/views/shared/_top_banner.html.erb
Welcome back <%= Userinfo.find_by(user_id: session[:user_id]).first_name.capitalize %>! <%= link_to "Log out", session_path('current'), method: 'delete' %> <%= link_to "Delete my account", user_path(session[:user_id]), method:'delete' %> <%= link_to "Add a product", new_product_path %> <%= link_to "My profile", user_path(session[:user_id]) %>

app/views/users/new.html.erb
<% if @errors %>

<% @errors.each do |error| %>

    <b><p><%= error.join(" ") %></p></b>

<% end %>

<% end %>


<%= form_for @user do |f| %>

    <p><%= f.label 'user_name', 'Email' %></p>
    <p><%= f.text_field 'user_name' %></p>

    <p><%= f.label 'password', 'Password' %></p>
    <p><%= f.password_field 'password' %></p>

    <p><%= f.label 'password_confirmation', 'Password Confirmation' %></p>
    <p><%= f.password_field 'password_confirmation' %></p>

    <%= fields_for Userinfo.new do |f| %>

        <p><%= f.label 'first_name', 'First Name' %></p>
        <p><%= f.text_field 'first_name' %></p>

        <p><%= f.label 'last_name', 'Last Name' %></p>
        <p><%= f.text_field 'last_name' %></p>

        <%= f.hidden_field 'active_status', value:1 %>

    <% end %>

    <p><%= f.submit %></p>

<% end %>

<p><%= link_to "Back", products_path %></p>

app/views/users/show.html.erb
<%= render 'shared/top_banner' %>
<p><%= link_to "Back", products_path %></p>
<h1>Here are your information:</h1>
<p>Email: <%= @user.user_name %></p>
<p>First name: <%= @user_info.first_name %></p>
<p>Last name: <%= @user_info.last_name %></p>
<p>You have <%= @count_products %> products currently in the marketplace</p>
<p>You have submitted <%= @count_reviews %> reviews</p>

<h2>Here are the products you have submitted:</h2>

<%= render "shared/show_products" %>